### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by philipgiuliani** [kim-company/flutter_braintree#1]
We should add a README to the project which explains:
* What this plugin does
* How it can be used
  * Flutter code
  * Necessary iOS project modifications
  * Necessary Android project modifications

**Comment by ersjoh** [comment]
I can add the iOS part, probably Wednesday. :-)

**Comment by atta1234** [comment]
at lest explain it, every where is brain tree, but no one tell about that nonce what's that,,,

**Comment by atta1234** [comment]
a guide to google pay, and paypal clint id etc will be very great!

**Comment by philipgiuliani** [comment]
Hi @atta1234 ,

we contributed a part of our implementation to the following library: https://github.com/Pikaju/FlutterBraintree (https://pub.dev/packages/flutter_braintree).

We will archive this project.
