### ISSUE TITLE
Is this production ready

### ISSUE THREAD

**Issue by gmaxferr** [kim-company/flutter_braintree#2]
Hello,

I haven't yet tried to use this plugin... is it production ready?
Not much content in the readme nor a single release, that is why I haven't yet tried it

Thanks,
Guilherme

**Comment by philipgiuliani** [comment]
Hi,

we are using the library in production, and it works well. Its just a simple wrapper around Braintrees Drop-In UI.

We still have to write the installation tutorial. You can follow the guide of Braintree.

**Comment by gmaxferr** [comment]
thank you! I had my doubts since it had a few commits and a small readme...
I'll try it then :+1:
